language: java
jdk:
- oraclejdk12
before_script: cd Server
before_deploy: cp -r ../Client/ ./
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: VUHsEHmUSelbewyhFS842j3i5LUoE1AqbFsn5Qh5oj4xuNdnQwSl6T5VcJl52SZJGCS3IFdGPMW/lA8ch0fSds9MXksGpeLG4JkiUzlolUhmG5hO3e7txl5u11LvZcRVLADXuUrJVWnCOdOU7nOXbGjO2IavFyuqeAb6x3XsHuz3tt6n1VN+jVHMZN7fkg4cl2B3FtM+Y7/JZfWFwCr0GNyolmkleJBbxGptMzPJejT1wLMf3WsE7pr1zXrSCwZ65rH3ap5x6Yw4eEm90YLv2emDGLYgUS3j+NUY623ZQ3tLFCzdFP5fL9wBJGQ3VGsxjUIvOnlM2QZ8jRBBab5MkCR3650E9/adV8W7nKduEufC2Ocjm4mU2CdvWGclmgfog9ROsj1WWU30nui7M0RFLyy8aVMAAXgf0WoZHl4x4NhF0pyYRUzIoKLr/YnxL1wAJfn8187QdITcC7aFR8RYkBwoPNG7iNp9mRKzpHujljw06fLLl4fC9xmQ3SbUl6Jg58xMcFxERkcwoHliBP532SluxwDoGo4qtsvillY6u19skBxw2jRMm7aB/pVp2TK8XoXZTKYfsBUi5f5R4tztva3yarNO6Dip61yv3lzoaDC+8weadrZuqnHhrGj53GdrMfVuTY8PswQNi5uhcrYTEhPShXrkphmvrSGjER1uHeo=
  app: rrgp
  skip_cleanup: true
  on:
    repo: 3g-soft/rrgp
    branch: develop
